I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 215, in script
    e "You've created a new Ren'Py game."
  File "game/userinterface/engine/screens.rpy", line 43, in execute
  File "game/userinterface/engine/screens.rpy", line 43, in execute
  File "game/userinterface/engine/screens.rpy", line 44, in execute
  File "game/userinterface/engine/screens.rpy", line 51, in execute
  File "game/userinterface/engine/screens.rpy", line 52, in execute
  File "game/userinterface/engine/screens.rpy", line 64, in execute
  File "game/userinterface/engine/screens.rpy", line 65, in execute
  File "game/userinterface/engine/screens.rpy", line 66, in execute
  File "game/userinterface/engine/screens.rpy", line 67, in execute
Exception: DynamicImage u'[type.getImage]': could not find image. (u'[defaultFolder]images/chars/michelle.png')

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 215, in script
    e "You've created a new Ren'Py game."
  File "renpy/ast.py", line 721, in execute
    renpy.exports.say(who, what, *args, **kwargs)
  File "renpy/exports.py", line 1419, in say
    who(what, *args, **kwargs)
  File "renpy/character.py", line 1249, in __call__
    self.do_display(who, what, cb_args=self.cb_args, dtt=dtt, **display_args)
  File "renpy/character.py", line 901, in do_display
    **display_args)
  File "renpy/character.py", line 647, in display_say
    rv = renpy.ui.interact(mouse='say', type=type, roll_forward=roll_forward)
  File "renpy/ui.py", line 298, in interact
    rv = renpy.game.interface.interact(roll_forward=roll_forward, **kwargs)
  File "renpy/display/core.py", line 3325, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, pause=pause, pause_start=pause_start, **kwargs)
  File "renpy/display/core.py", line 3737, in interact_core
    root_widget.visit_all(lambda i : i.per_interact())
  File "renpy/display/core.py", line 568, in visit_all
    d.visit_all(callback, seen)
  File "renpy/display/core.py", line 568, in visit_all
    d.visit_all(callback, seen)
  File "renpy/display/core.py", line 568, in visit_all
    d.visit_all(callback, seen)
  File "renpy/display/screen.py", line 436, in visit_all
    callback(self)
  File "renpy/display/core.py", line 3737, in <lambda>
    root_widget.visit_all(lambda i : i.per_interact())
  File "renpy/display/screen.py", line 447, in per_interact
    self.update()
  File "renpy/display/screen.py", line 637, in update
    self.screen.function(**self.scope)
  File "game/userinterface/engine/screens.rpy", line 43, in execute
  File "game/userinterface/engine/screens.rpy", line 43, in execute
  File "game/userinterface/engine/screens.rpy", line 44, in execute
  File "game/userinterface/engine/screens.rpy", line 51, in execute
  File "game/userinterface/engine/screens.rpy", line 52, in execute
  File "game/userinterface/engine/screens.rpy", line 64, in execute
  File "game/userinterface/engine/screens.rpy", line 65, in execute
  File "game/userinterface/engine/screens.rpy", line 66, in execute
  File "game/userinterface/engine/screens.rpy", line 67, in execute
  File "renpy/sl2/sldisplayables.py", line 440, in sl2add
    d = renpy.easy.displayable(d, scope=scope)
  File "renpy/easy.py", line 113, in displayable
    return renpy.display.image.DynamicImage(d, scope=scope)
  File "renpy/display/image.py", line 571, in __init__
    self.find_target(scope)
  File "renpy/display/image.py", line 652, in find_target
    raise Exception(error)
Exception: DynamicImage u'[type.getImage]': could not find image. (u'[defaultFolder]images/chars/michelle.png')

Windows-10-10.0.22000
Ren'Py 7.4.11.2266
CharacterQuestManager 1.0
Fri May 20 16:56:10 2022
